version: "3.4"
services:
  webserver:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: production
    command: sh /app/docker/entrypoint.production.sh
    ports:
      - 3000:3000
    environment:
      PRODUCTION: 'true'
